#!/bin/bash
#SBATCH --job-name eSLAM_Filtering_Third_part
#SBATCH --time 1:00:00
#SBATCH --nodes 1
#SBATCH --cpus-per-task 48
#SBATCH --output eSLAM_Filtering_Third_part.%A_%a.log
#SBATCH --array 1-28

# Load Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../config.sh"

echo "PART 4 (B) of SLAM-SEQ Analysis: Categorize BAM by Mutation Count"
echo "This script creates sorted BAM files for reads containing 1, 2, 3, 4, or >4 mutations."


INDIR_RAW="${RAW_DATA_DIR}"
OUTDIR_HISAT="${HISAT3N_OUTPUT_DIR}"
OUTDIR_MISMATCH="${OUTDIR_HISAT}/mismatch_infos"
FILELIST="${SAMPLE_FILELIST}"


# Ensure required sample lists and Step 4A output files exist before starting.
if [[ ! -f "$FILELIST" ]]; then
    echo "ERROR: filelist.txt not found at ${FILELIST}."
    exit 1
fi

FILE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${FILELIST}")
INPUT_BAM="${OUTDIR_HISAT}/${FILE}_aligned.unique.filtered.sorted.bam"

if [[ ! -f "$INPUT_BAM" ]]; then
    echo "ERROR: Filtered BAM file not found for ${FILE} at ${INPUT_BAM}."
    echo "Did Step 4A finish successfully?"
    exit 1
fi

echo "Processing sample: ${FILE}"

# Load Modules
module load gcc
module load samtools


# Iterate through mutation count tables generated by splbam.py in Step 4A 
# (1, 2, 3, 4, >4 T->C conversions), extracts matching reads into separate 
# BAM files, sorts, indexes, and cleans up temporary files.

for idx in "${MUTATION_CATEGORIES[@]}"; do
    TAB_FILE="${OUTDIR_MISMATCH}/${FILE}.Yf.table.${idx}.tab"
    
    if [[ ! -f "$TAB_FILE" ]]; then
        echo "WARNING: Read list ${TAB_FILE} not found. Skipping category '${idx}'."
        continue
    fi

    echo "--- Processing category: ${idx} mutation(s) ---"

    UNSORTED_BAM="${OUTDIR_HISAT}/${FILE}_aligned.unique.filtered.${idx}.bam"
    SORTED_BAM="${OUTDIR_HISAT}/${FILE}_aligned.unique.filtered.sorted.${idx}.bam"

    # Extract reads based on read names in the table file
    echo "Extracting reads..."
    samtools view -h -b --threads "${SLURM_CPUS_PER_TASK}" \
        -N "${TAB_FILE}" \
        "${INPUT_BAM}" > "${UNSORTED_BAM}"

    # Sort and index categorized BAM
    echo "Sorting and indexing..."
    samtools sort --threads "${SLURM_CPUS_PER_TASK}" \
        -o "${SORTED_BAM}" \
        "${UNSORTED_BAM}"

    samtools index -@ "${SLURM_CPUS_PER_TASK}" "${SORTED_BAM}"

    # Remove unsorted intermediate BAM file
    echo "Removing unsorted intermediate file..."
    rm -f "${UNSORTED_BAM}"
done

echo "Script finished successfully"
